config/routes.rb
Rails.application.routes.draw do
  resources :cats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root to: "cats#index"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
class Cat < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.ransackable_attributes(auth_object = nil)
    ["age", "created_at", "id", "id_value", "name", "updated_at"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: %i[ show edit update destroy ]

  # GET /cats
  def index
    @search = Cat.ransack(params[:q])
    @search.sorts = 'id desc' if @search.sorts.empty?

    @cats = @search.result.page(params[:page])
  end

  # GET /cats/1
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to @cat, notice: "ネコを登録しました"
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cats/1
  def update
    if @cat.update(cat_params)
      redirect_to @cat, notice: "ネコを更新しました", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /cats/1
  def destroy
    @cat.destroy!
    redirect_to cats_url, notice: "ネコを削除しました", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cat_params
      params.require(:cat).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sidebar_link_to(path, emoji, text)
    classes = %w[my-1 text-white font-bold flex rounded py-2]
    classes << "bg-blue-600" if current_page?(path)

    link_to(path, class: classes) do
      tag.span(class: "mx-2") { emoji } + tag.span { text }
    end
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/application/_flash.html.erb
<div class="mt-4">
  <% if notice %>
    <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
      <button type="button" class="absolute top-0 right-0 px-4 py-3">
        <svg class="fill-current h-6 w-6 text-blue-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 5.652a.5.5 0 0 0-.707 0L10 9.293 6.36 5.652a.5.5 0 0 0-.707.708L9.293 10l-3.64 3.641a.5.5 0 0 0 .707.707L10 10.707l3.641 3.64a.5.5 0 0 0 .707-.707L10.707 10l3.64-3.641a.5.5 0 0 0 0-.707z"/></svg>
      </button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-4" role="alert">
      <button type="button" class="absolute top-0 right-0 px-4 py-3">
        <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 5.652a.5.5 0 0 0-.707 0L10 9.293 6.36 5.652a.5.5 0 0 0-.707.708L9.293 10l-3.64 3.641a.5.5 0 0 0 .707.707L10 10.707l3.641 3.64a.5.5 0 0 0 .707-.707L10.707 10l3.64-3.641a.5.5 0 0 0 0-.707z"/></svg>
      </button>
      <%= alert %>
    </div>
  <% end %>
</div>

app/views/application/_sidebar.html.erb
<div class="flex flex-col flex-shrink-0 bg-[#343a40] h-full p-3">
  <div class="flex items-center justify-center py-2">
    <%= link_to "AMS", root_path, class: "text-white text-3xl font-semibold" %>
  </div>

  <hr class="h-px bg-gray-200 border-0">

  <ul class="flex flex-col mt-4 gap-4">
    <li>
      <%= sidebar_link_to(cats_path, "😺", "ねこ") %>
    </li>
    <li>
      <%= sidebar_link_to(root_path, "🐶", "いぬ") %>
    </li>
    <li>
      <%= sidebar_link_to(root_path, "🐣", "ひよこ") %>
    </li>
    <li>
      <%= sidebar_link_to(root_path, "🦔", "ハリネズミ") %>
    </li>
    <li>
      <%= sidebar_link_to(root_path, "🦉", "フクロウ") %>
    </li>
  </ul>
</div>

app/views/cats/_cat.html.erb
<div class="grid grid-cols-3 py-2 border-t">
  <div class="flex items-center">
    <%= cat.name %>
  </div>

  <div class="flex items-center">
    <%= cat.age %>
  </div>

  <div class="flex gap-2 justify-end">
    <%= link_to "編集", edit_cat_path(cat), class: "py-1 px-2 text-blue-500 border border-blue-500 rounded" %>
    <%= button_to "削除", cat, method: :delete, class: "py-1 px-2 text-red-500 border border-red-500 rounded" %>
  </div>
</div>

app/views/cats/_form.html.erb
<%= form_with(model: cat) do |form| %>
  <% if cat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
        <% cat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>ねこを編集する</h1>

<%= render "form", cat: @cat %>

<br>

<div>
  <%= link_to "詳細", @cat %> |
  <%= link_to "戻る", cats_path %>
</div>

app/views/cats/index.html.erb
<h1 class="font-bold">
  <span>😺</span>
  <span>ねこ</span>
</h1>

<div class="py-2 px-4 mt-3 rounded shadow">
  <div>
    検索条件
  </div>

  <div class="mt-2">
    <%= search_form_for @search, html: { class: "flex gap-2" } do |f| %>

      <%# `カラム名_cont`とすることで、カラムに対してLIKEを使った曖昧一致検索ができる %>
      <%= f.label :name_cont, "名前" %>
      <%= f.search_field :name_cont, class: "border rounded" %>

      <%# `カラム名_eq`とすることで、カラムに対して完全一致検索ができる %>
      <%= f.label :age_eq, "年齢" %>
      <%= f.search_field :age_eq, class: "border rounded" %>

      <div class="py-1 px-2 rounded text-white bg-blue-500">
        <%= f.submit %>
      </div>

      <%# 検索結果と検索フォームをクリアする %>
      <div class="py-1 py-2 rounded border border-blue-500 text-blue-500">
        <%= link_to "リセット", cats_path %>
      </div>
    <% end %>
  </div>
</div>

<div class="py-2 px-4 mt-3 rounded shadow">
  <div class="grid grid-cols-3 mb-2">
    <div class="flex items-center text-blue-500">
      <%= sort_link(@search, :name) %>
    </div>
    <div class="flex items-center text-blue-500">
      <%= sort_link(@search, :age) %>
    </div>
    <div class="flex justify-end">
      <%= link_to "登録", new_cat_path, class: "py-1 px-2 rounded text-blue-500 border border-blue-500" %>
    </div>
  </div>

  <%= render @cats %>
  <%= paginate @cats %>
</div>

app/views/cats/new.html.erb
<h1>New cat</h1>

<%= render "form", cat: @cat %>

<br>

<div>
  <%= link_to "Back to cats", cats_path %>
</div>

app/views/cats/show.html.erb
<%= render @cat %>

<div>
  <%= link_to "Edit this cat", edit_cat_path(@cat) %> |
  <%= link_to "Back to cats", cats_path %>

  <%= button_to "Destroy this cat", @cat, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div class="min-h-screen flex">
      <div class="w-1/4">
        <%= render "sidebar" %>
      </div>
      <div class="flex-1 my-4 px-2">
        <%= render "flash" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>